# Rolling windows
SHORT_WINDOW = 90
LONG_WINDOW = 252

# Diversification Score thresholds
SCORE_HEALTHY = 75
SCORE_MODERATE = 50

# Cluster detection
CLUSTER_CORRELATION_THRESHOLD = 0.6
TOP_CLUSTER_CONCENTRATION_THRESHOLD = 0.60

# Correlation regime thresholds
CORRELATION_TIGHTENING = 0.15
CORRELATION_COMPRESSION = 0.20

# Stress multiplier thresholds
STRESS_FRAGILITY = 1.4
STRESS_HIGH_FRAGILITY = 1.6

# Action thresholds
CLUSTER_TRIM_THRESHOLD = 0.55
CLUSTER_AVOID_THRESHOLD = 0.35
DEFENSIVE_MIN_THRESHOLD = 0.15

# EMA smoothing period
EMA_SMOOTHING_PERIOD = 7
